# Generated by Django 2.1.2 on 2018-10-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alergia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=6)),
                ('fecha_nacimiento', models.DateField()),
                ('sala_piso', models.CharField(max_length=100)),
                ('receta', models.CharField(max_length=100)),
                ('expediente', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, upload_to='imagen_perfil')),
                ('alergias', models.ManyToManyField(to='Alergia.Alergia')),
            ],
        ),
    ]
