# Generated by Django 2.1.2 on 2018-11-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0003_auto_20181031_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagen_perfil'),
        ),
    ]
