# Generated by Django 2.1.2 on 2018-11-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0004_auto_20181031_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='imagen',
            field=models.ImageField(default='imagen_perfil/default.jpg', upload_to='imagen_perfil'),
        ),
    ]
